spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://auth-db:5433/auth_service_db
    driverClassName: org.postgresql.Driver
    username: auth_service
    password: auth_service_pass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: suuuuuuuuuupppperrrr-secret-keyyyyyyyyyy
  expiration: 3600000

user-service:
  url: http://user-service:8080

server:
  port: 8081